# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Gopal Ghimire
tagline: Student
pic: 20151117_112758.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Hello, My name is Gopal Ghimire. I live in Biratnagar, Nepal, actually belongs to Shankuwa-shava district. I am student of the 
science of technology. The name of my college university is Purbanchal university school of engineering and technology(PUSET).
I have no any job becouse i am still studying.'

#sidebar links
email: gopal.ghimire332@gmail.com
phone: 9819356415
linkedin: gopal.ghimire332
github: Gopalghimire1
twitter: '@gopalghimire19'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
